services:
  kb_web:
    build:
      context: /srv/projects/kb
      dockerfile: Dockerfile
    container_name: kb_web
    env_file: /srv/projects/kb/.env
    networks: [web]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/projects/kb/data/www:/srv/projects/kb/data/www:ro
      - /srv/projects/kb/data/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/projects/kb/data/ssl:/srv/projects/kb/data/ssl:ro
      - /srv/projects/kb/data/storage:/srv/projects/kb/data/storage
      - /srv/projects/kb/data/db:/srv/projects/kb/data/db
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  web:
    external: true
