version: "3.9"

services:
  kb_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowlab_web
    env_file:
      - .env
    environment:
      FILES_ROOT: /srv/projects/kb/data/files
      OLLAMA_BASE_URL: http://127.0.0.1:11434
      QDRANT_URL: http://127.0.0.1:6333
    ports:
      - "80:80"
      - "443:443"
      - "11434:11434"
      - "6333:6333"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/projects/kb/data/files:/srv/projects/kb/data/files
      - /srv/projects/kb/data/www:/srv/projects/kb/data/www
      - /srv/projects/kb/data/ssl:/etc/nginx/ssl:ro
      - /srv/projects/kb/data/storage/ollama:/srv/projects/kb/data/storage/ollama
      - /srv/projects/kb/data/storage/qdrant:/srv/projects/kb/data/storage/qdrant
      - /srv/projects/kb/data/logs/api:/srv/projects/kb/data/logs/api
      - /srv/projects/kb/data/logs/nginx:/var/log/nginx
      - /srv/projects/kb/data/logs/ollama:/srv/projects/kb/data/logs/ollama
      - /srv/projects/kb/data/logs/qdrant:/srv/projects/kb/data/logs/qdrant
      - /srv/projects/kb/data/logs/supervisor:/srv/projects/kb/data/logs/supervisor
    restart: unless-stopped
