[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log

[program:ollama]
environment=OLLAMA_HOST=127.0.0.1:11434,HOME=/srv/projects/kb
command=/usr/local/bin/ollama serve
directory=/srv/projects/kb/data/storage/ollama
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:api]
command=/opt/venv/bin/uvicorn app.main:app --host 127.0.0.1 --port 8080 --proxy-headers --log-level=info
directory=/srv/projects/kb
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g 'daemon off;'
autorestart=true
startretries=10
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
