services:
  kb_web:
    build: .
    container_name: kb_web
    env_file:
      - .env
    networks:
      - web
    volumes:
      - /srv/projects/kb/app:/srv/projects/kb/app
      - /srv/projects/kb/data/files:/srv/projects/kb/data/files
      - /srv/projects/kb/data/storage:/srv/projects/kb/data/storage
      - /srv/projects/kb/data/logs:/srv/projects/kb/data/logs
      - /srv/projects/kb/data/ssl:/srv/projects/kb/data/ssl
    ports:
      - "80:80"
      - "443:443"
      - "11434:11434"
      - "6333:6333"

networks:
  web:
    external: true
